import Footer from "./components/Footer";
import Nav from "./components/Nav";
import "./globals.css";
import { SpeedInsights } from "@vercel/speed-insights/next";
import { ThemeProvider } from "next-themes";

export const metadata = {
  title: "Portfolio",
  description: "Generated by create next app",
};

export default function RootLayout({ children }) {
  return (
    <html lang="en">
      <body>
        <ThemeProvider attribute="class">  {/* Enables dark mode */}
          <Nav />
          {children}
          <SpeedInsights />
          {/* <Footer /> */}
        </ThemeProvider>
      </body>
    </html>
  );
}
