import Footer from "./components/Footer";
import Nav from "./components/Nav";
import "./globals.css";
import { SpeedInsights } from "@vercel/speed-insights/next"

export const metadata = {
  title: "Portfolio",
  description: "Generated by create next app",
};

export default function RootLayout({ children }) {
  return (
    <html lang="en">
      <body>
        <Nav/>
        {children}
        <SpeedInsights />
        {/* <Footer/> */}
      </body>
    </html>
  );
}
